services:
  backend:
    build:
      context: ../backend
    container_name: se2025_backend
    ports:
      - "3000:3000"
    env_file:
      - ../docker/.env
    restart: unless-stopped
    networks:
      - my_ipv6_net

networks:
  my_ipv6_net:
    external: true
